steps:
  # Step 1: Build the container image (Note the './backend' at the end)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/grid-wallpaper/my-repo/kaizengrid-backend', './backend']

  # Step 2: Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/grid-wallpaper/my-repo/kaizengrid-backend']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kaizengrid-backend'
      - '--image'
      - 'asia-south2-docker.pkg.dev/grid-wallpaper/my-repo/kaizengrid-backend'
      - '--region'
      - 'asia-south2'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY